### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by Cobravs** [VickyGit/topo#1]
D:\Repository\github\topo>npm run dev

> topo@1.0.0 dev D:\Repository\github\topo
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js --host 192.168.1.117

 10% building modules 1/1 modules 0 activeevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 192.168.1.117:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! topo@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js --host 192.168.1.117`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the topo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by VickyGit** [comment]
1、open the file with the name： package.json
2、and find the line： "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js --host  192.168.1.117",
3、delete ：--host  192.168.1.117"   or change to your ip。
4、run npm run dev
5、ok

**Comment by asenv587** [comment]
哥们，你这个项目点击那个圆  会报错。
